#3 დაბეჭდე ყველა მათემატიკური მოქმედება წინა დავალებაში შექმნილ ცვლადებზე (+, -, *, /, %, //)
num1 = int(input("enter your age" ))
num2 = int(input("enter your number"))

print ( num1 + num2)
print( num1 - num2)
print ( num1 * num2)
print( num1 / num2)
print (num1 % num2)
print ( num1 // num2)